# -*- coding: utf-8 -*-
"""CHP_06_Strings

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IZGT9qDWTOjioAnzy4xIVLcWUZDkJOAr
"""

# String is a data type that stores sequence of characters
#eg string statement

str1="Hello my name is Atharva! \n This is my world!!"
print(str1)

#operations performed in a string are :

#1. Concatenation - It is the process of joining two strings
# eg code

str1="Atharva"
str2="Technologies"
final_string=(str1+str2)

print(final_string)

#2. 'len' - used to find the length of the string
#eg code
str1="Atharva"

print(len(str1))

#eg code 2

str1="Hamilton"
len1=(len(str1))

print(len1)

#INDEXING - these are basically positions assigned to the characters of the string
#Indexing is always done from zero (0,1,2,3,4,5......and soo on)

#eg code

str1="Atharva"

cha=str1[4] #made a variable cha tht contains the statement that asks for 4 index in string (str1)

print(cha)

#SLICING - It is a method used to access parts of a string

# eg of slicing statement -- str[starting_idx:ending_idx] (ending index is not included )
#eg code

str1 = "Atharva"

print(str1[1:4]) # the o/p will only print from index 1 to index 3 wont print the last index

#SPECIAL CASE OF SLICING - NEGATVE INDEXING

#eg code

str1 = "Apple"

print(str1[-4:-1])

#FUNCTIONS OF STRING (.endswith("er"),.capitalize(),.replace(old,new),.find(word),.count("am"))
# After using these functions the o/p will either be True or False depending upon the condition
#eg code

#endswith("")
str1 = "I am studying Python"

print(str1.endswith("hon"))


#capitalize().......used to capitalize a satement

str2 = "python"

str2=(str2.capitalize())
print(str2)

#replace(old,new).......used t replace old value with new

str3 = "I love Python"

print(str3.replace("Python","SQL"))

#find(word).... checks if the word actally exists in the string or not

str4="Hello world"

print(str4.find("d"))

#count()......this function returns how many times the word exists in our string

str5="I am studying Python"

print(str5.count("t"))