# -*- coding: utf-8 -*-
"""chp_09_Tuples

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NfHBBb0wHRIuGlT6vSpU3kKquoLY_KVw
"""

# TUPLES - It is a built in Data type that lets user create immutable data type
# Tuples are immutable it means they cannot mutate and change valuse like Lists
# Tuples are represented by '()' brackets

#eg

val = (1,4,5,6)

print(type(val))


# how do we access indexes in tuples

var1 = (1,4,5,6)
print(var1[0])

# TUPLE METHODS

#1 .index() - this function tells the index/first occurance of the number

#eg

tup1 = (9,0,3,4,5,6)

print(tup1.index(3))

#2 .count() - this function tells the total number of times the value has occured in the tuple

#eg

tup2 = (3,4,5,6,7,2,3,3,3,3,4,5,6,6,6,6,6,6)
print(tup2.count(3))

