# -*- coding: utf-8 -*-
"""chp_08_Lists

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tp1yegHuKR9VVMbXvAXoLWWC-NZX6EaP
"""

#LISTS - It is a built in data type that stores values
#It can store elements of different types (integer , float , string etc.)
# Lists are always represented by '[]' brackets

marks = [99.8,87.2,88,67.68,100]
print(marks)
print(type(marks))
print(len(marks))

#Indexing concept in Lists

print(marks[0])
print(marks[3])

# List slicing

marks = [40,52.6,99.99,93.56,78.23]

print(marks[-3:-1])
print(marks[1:4])

# LIST METHODS - (.append() , .sort() , .reverse() , .insert())


# .append() function

list = [1,3,4,6]
list.append(10) # by this it will add the number to the list
print(list)

# .sort() function (this function will automatically sort the list in the ascending order)

list1 = [3,2,8,6,5,0]
list1.sort()
print(list1)


# .sort(reverse=True) function (this function will automatically sort the list in descending order)

list2 = [1,2,3,4,5,6,7]
list2.sort(reverse=True)
print(list2)

#now trying sorting with string values

list3 = ['Apple','Pineapple','Apricot','Banana']
list3.sort()
print(list3)


# .reverse() function  (This function completely reverses the give list)

list4=['Apple','Samsung','Oneplus','Google']
list4.reverse()
print(list4)


# .insert() function   (This inserts a value be it string or int ,float, but only at a particular index)

list5=['Apple','Oneplus','Google']
list5.insert(1,'Samsung')
print(list5)


# .remove() function   (This fucntion removes occurance of an element)

list6=[1,3,4,8]
list6.remove(3)
print(list6)


# .pop() function  (This function removes and element from a particular index)

list7 = [3,4,5,6,7]
list7.pop(2)
print(list7) # it removed 5 as it was at index 2