# -*- coding: utf-8 -*-
"""chp_10_Dictionary

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FVZrp7APTi9DZl0ZxN03pEHWQAA0Do0H
"""

#DICTIONARY - These ae used ot store data values in key:value pairs
#They are unordered , mutable and dont allow duplicate keys
# dictionary always works in form of pairs

# dictionary depicted by '{}' brackets

#eg

info = {
    "Name":"Atharva",
    "Age":21,
    "Profession":"Data Analyst"
}

print(info)
print(type(info))

# Adding / inserting more key value pairs in the dictionary

dict1 = {
    "name":"Atharva",
    "age": 21,
    "Profession":"Data Analyst"
    }



dict1["name"] = "Arthur"  # This over write the olf variable in the dictionary

print(dict1)

# CONCEPT OF 'NESTED DICTIONARY'
# In this we can make a dictionary within a key value pair of a dictionary


#eg

dict2 = {
    "student name":"Atharva",
    "ID":"04",
    "subject marks":{
        "math":"20/20",
        "physics":"19/20",
        "chemistry":"19/20"
    }
}

print(dict2)

# METHODS IN DICTIONARY

# .keys() - This fucntion returns all keys in the dictionary

dict1 = {
    "Rank":"01",
    "Name":"Atharva",
    "Age":"22"
}

print(list(dict1.keys())) # writing list in order to keep our final o/p in a list


# .values() - This function returns all the values of the keypairs in the dictionary

dict1 = {
    "Rank":"01",
    "Name":"Atharva",
    "Age":"22"
}

print(list(dict1.values()))


# .items() - This function returns all key value pairs as tuples

dict1 = {
    "Rank":"01",
    "Name":"Atharva",
    "Age":"22"
}

print(dict1.items())


# .get() - This function returns the key according to the value

dict1 = {
    "Rank":"01",
    "Name":"Atharva",
    "Age":"22"
}

print(dict1.get("Name"))


# .update() - This function inserts a new specified item to the dictionary

dict1 = {
    "Rank":"01",
    "Name":"Atharva",
    "Age":"22"
}

dict1.update({"City":"Mumbai"})

print(dict1)