# -*- coding: utf-8 -*-
"""CHP-02 Data Types

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H5qKhW-9FBnREMVNqHMBRS7-q1NiTjoq
"""

#here we declared some variables
name = 'Arthur'
age = 21
weight = 78.98

#Example 01
#now by using'type'we will find the data type of the varibale data i.e.(int,str,float,bool)
print(type(name))
print(type(age))
print(type(weight))

#Example02

profession="Doctor"
old = False
a = None

print(type(old))
print(type(None))