# -*- coding: utf-8 -*-
"""chp_07_conditional statements

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PkGOu1VzHKGDNx5rrOX0UYMtcRKKpU5K
"""

#CONDITIONAL STATEMENTS ie. ( if , elif , else )

# if satatement

age = 22

if(age>=18):
  print("You are eligible to vote!")
  print("You are eligible to apply for the driver permit . ")

# elif statement (aka : else if)
# this statement implies that if the previous condition does not work check for the other condition
# elif condition only implies and checks when the if statement is false .


light = "Yellow"

if(light=="Red"):            # here we put two '==' in order to compare the statement and condtion
  print("STOP")
elif(light=="Green"):
  print("GO")
elif(light=="Yellow"):
  print("GO SLOW")

print("End of code")

#eg 02

num = 20

if(num>=15):
  print("Large input number")

#else statement
#this comes into picture when all the above conditions ie. elif , if fail to satisfy the condition
#else statement always comes in the end and prints the variable or value assigned to it
#basically else statement is the last resort

#eg code :

car = ("BIKE")

if(car=="SEDAN"):
  print("Parking available")

elif(car=="SUV"):
  print("Parking available")

elif(car=="HATCHBACK"):
  print("Parking available")

else:
  print("No parking available") # Since none of the above available statements were true to the i/p value it printed the else statement

#EXAMPLE CODE FOR CONDITIONAL STATEMENTS (MASTER PROBLEM)

marks=(78)

if(marks>=90):
  print("Grade : A")

elif(90>marks>=80):
  print("Grade : B")

elif(80>marks>=70):
  print("Grade : C")

elif(70>marks>=40):
  print("Grade : D")

else:
  print("Fail")

# CONCEPT OF  'NESTING'
# nesting means writing one conditional statement in another ie. writing an if statement under if

# eg 01

age = 90

if(age>=18):
  if(age>=80):
    print("Cannot Drive !")

  else:
    print("Can drive ! ")

