# -*- coding: utf-8 -*-
"""chp_10_sets

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1USFjwRQkGrfCBPcC1H5fT_P2D6A219HV
"""

# Set - It is a collection of unique and immutable elements .
# In sets each and every element is unique
# Set is reperesented by '{}' curly braces
# Set automatically discards duplicate values
# while siplaying values Set does not follow any order it randomly places elements

#eg

collection = {1,2,3,4,5}

print(type(collection))
print(collection)

#eg : shows how set discards duplicate values

set1 = {"Orange","Apple","Apple","Pineapple","Mango"}

print(type(set1))
print(len(set1))
print(set1)

# how do we print an empty Set ??

#If we write

set0={}
print(type(set0)) #It will show that it is a dictionary

#Therefore we write it as :

# Delete the shadowed 'set' variable to restore the built-in set function
del set

collection = set()

print(type(collection))

# Functions in Sets

#1 .add()  - This function helps in adding an element from the set

collection = set()
collection.add(1)
collection.add(2)
collection.add(2)   # this value will be discarded as it is a duplicate
collection.add(3)

print(collection)


#2 .remove()  - This function helps in removing an element from the set

set5 = {1,2,3,4,5}

set5.remove(3)

print(set5)


#3 .clear()  - This function helps in emptieing the set

set6 = {1,2,3,4,5}

set6.clear()

print(set6)


#4 .pop(). - This method is used to pop/remove a random valur from the set
# Note : when .pop() is used it removes a random value

set7 = {1,2,3,4,5,6,7,"Apple","Mango","Kiwi"}

print(set7.pop())


#5 .union(set2/the second respective set) - This function helps in combining two sets and give a new o/p set tht is the combination of the two

set1={1,2,3,4,5}
set2={6,7,8,9,10}

print(set1.union(set2))


#6 .intersection()  - This function helps to print the common values out of the two sets

set3={1,2,3,4,5}
set4={2,4,5,6,8}

print(set3.intersection(set4))