# -*- coding: utf-8 -*-
"""Type Conversion and Type Casting

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WXjimbJpyJp2ZIhCMgym0YGSMmww_jLM
"""

#TYPE CONVERSION - It is the conversion of one type of variable to another i.e (int---->float)
#type conversion is usually done automatically , no user intervention requiered

#Type conversion eg
a=10
b=5.55
sum = (a+b)
print(sum) #here python will automatically convert the a variable in float to facilitate the sum of the two variables

#TYPE CASTING - Here the conversion is done manually by the user

#Type casting eg ----->

a=float("10")  #Here we force type casting and manually convert b variable to int value
b=20.567
print(a+b)

#Type casting eg 2 ------>

val1=2
val2=int(float('4.555')) # converting the float value to integer

sum=(val1+val2)

print(sum)