# -*- coding: utf-8 -*-
"""CHP-03 Operators

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KQTLS56gaP3cGbKDNCXfGiOhnFIl2XL0
"""

# ARITHMATIC OPERATORS i.e. (+,-,*,/,%)
a=40
b=20
sum=(a+b)
difference=(a-b)
multiply=(a*b)
division=(a/b)
remainder=(a%b)
power=(a**b) #---- a^b

print(sum)
print(difference)
print(multiply)
print(division)
print(remainder)
print(power)

#RELATIONAL OPERATORS i.e(==,!=,>,<,>=,<=)

a=50
b=60

print(a==b) #This operator '==' is for checking if a is equal to b or not
print(a!=b) #This operator '!=' is for checking if a is not equal to b
print(a>=b )#This operator '>=' is for checking if a is greater than b or not
print(a<=b)#This operator is for checking if a is less tha or equal to b or not

#ASSIGNMENT OPERATORS i.e(=,+=,-=,*=,/=,%=,**=)

#how normally we would write a code without assignment operator
#num = 10
#num = (num + 10)
#print(num)

#now with assignment operator

num = 10
num += 10
#num -= 10 this will decrement the num variable by 10
#num *= 10 this will multiply the value of num variable by 10
#num /= 10 this will divide
#num %= 10 this will give the remainder upon diving
#num **= 10 this will power
print(num) #This operator here will increment the num variable by 10

#LOGICAL OPERATOR i.e(not,and,or)

# not - returns the opposite of the given boolean
# and - returns the real answer after checking the two conditions
# or - it will check if either of the conditions are true ,atleast 1 variable must be true


# eg code for not operator
print(not False)
print(not True)

#eg code for and operator
a=True
b=True
print("Result: ",a and b)

#eg code for or operator
a=True
b=False
print("Result: ",a or b)