# -*- coding: utf-8 -*-
"""Inputs in python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11QT4IYQfO2P-wsHLQo7M4QSZq26v9txL
"""

#Input statement is used to accept values from the user (from the values he types from his key board)

#eg statement

name=input("Enter your name: ")
print("Welcome",name)

#eg statement 2

age=input("Enter any value here:  ") #input statement value is always considered string by default
print(type(age),age) #even though we had a integer here it returned answer as string

#eg statement 3

#now we will manually tell the input statement that the nput is supposed to be an integer

age=int(input("Enetr your age here :  "))
print(type(age))

#eg statement

name=input("Enter your name here: ")
age=int(input("Enter your age here: "))
weight=float(input("Enter your weight here: "))

print("Welcome back: ",name)
print("age: ",age)
print("weight: ",weight)