# -*- coding: utf-8 -*-
"""practise_prob_05

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17lYH5iNvgjLMQqXZCkM1FnssBkvuzvYH
"""

#WAP to check if the number entered by the user is even or odd

value = int(input("Enter the value here :  "))
even = (value % 2==0)
odd = (value % 2!=0)

if(value % 2==0):
  if(value % 2!=0):
    print("value given at i/p is odd")
  print("Value given at o/p is even")