# -*- coding: utf-8 -*-
"""practise_prob_04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13P6j-04Gjmm8BvIpu2oxOpGGlmFDYQw-
"""

# WAP to find occurence of "S" in a string

str1 = "She sells sea shells by the sea shore"
print(str1.count("s"))