# -*- coding: utf-8 -*-
"""practise_prob_08

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a-_vo2udU01FwzyIpGHMXZN-pkZv_BjB
"""

# WAP to check if a list contains palindrome of elements
#(palindrome - it is a string that spells and looks same from front to end and end to front eg - ma'am)

#Hint: Use copy() method


list1 = [1,2,3,5,6,7]

list2 = [1,1,2,2,1,1]

copy_list1 = list1.copy()
copy_list1.reverse()

if (list1==copy_list1):
  print(" List1 is a Palindrome")

else:
  print("List1 is not a Plaindrome")

copy_list2 = list2.copy()
copy_list1.reverse()

if(list2==copy_list2):
  print("List2 is a Palindrome")

else:
  print("List2 is not a Plaindrome")