# -*- coding: utf-8 -*-
"""practise_prob_06

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SjJx-wVZpDcvCAMIrCUaad_cZGme3Mif
"""

# WAP to find the greatest among 3 numbers entered by the user

val1 = int(input("Enter the first value here :  "))
val2 = int(input("Enter the second value here :  "))
val3 = int(input("Enter the third value here : "))

greatest = max(val1,val2,val3)

print("The greatest value is : ", greatest)