# -*- coding: utf-8 -*-
"""practise_prob_02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xrVh1yYVyusf3q8oM0Z9KO7D4hCZWc4K
"""

#WAP to input 2 numbers and print their sum

num1=float(input("Enter the first value: "))
num2=float(input("Enter the second value: "))

sum=(num1+num2)

print("The calculated value is: ",sum)