# -*- coding: utf-8 -*-
"""practise_prob_10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ERsV8tAFNa47bm8wIKgNz1Q6xHGfNqCV
"""

#WAP for:
# you are given a list of subjects for students . Assume one classroom is requiered for 1 subject . How many classrooms are neededby all students


subjects = {"Python","Java","C++","Python","Java script","Java","Python","Java","C++","C"}

print(subjects)
print(len(subjects))
print("Classrooms requiered are : 5 ")