# -*- coding: utf-8 -*-
"""practise_problem_09

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zMq3KhBbX-ebHojChyg_uSEOTYaeZdV6
"""

# WAP to store the following word meanings in python dictionary
# table : "a piece of furniture " , "A list of facts and figures"
# cat : "A small animal"

dict1={
    "table":["a piece of furniture","A list of facts and figures"],
    "cat":"A small animal"
}

print(dict1)