# -*- coding: utf-8 -*-
"""Practise prob 01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jKsYwdmZO-nwSiUQA9TehkVk04wsoaPB
"""

#Q1) print sum of 2 numbers

a=50
b=40

sum=(a+b)

print(sum)