# -*- coding: utf-8 -*-
"""practise_prob_03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MhLO60cCOHxsMY8yTi_uTYAHyp02dGv7
"""

# WAP to input users first name and print its length

input = input("Enter your first name here :  ")

print(input,len(input))