# -*- coding: utf-8 -*-
"""practise_prob_11

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r6Jv781Q2TZDrK99v6nK4OZXgkSHK2Cy
"""

# WAP to enter marks of 3 subjects from the user and store them in a dictionary
# Start with a an empty dictionary and add one by one . Use subject name as key
# and marks as values

Math = (input("Enter marks for Math here : "))
Chemistry = (input("Enter marks for Chemistry here : "))
Physics = (input("Enter marks for Physics here : "))

dict0 = {}

dict1={"Math":Math}
dict2={"Chemistry":Chemistry}
dict3={"Physics":Physics}

dict0.update(dict1)
dict0.update(dict2)
dict0.update(dict3)

print(dict0)