# -*- coding: utf-8 -*-
"""practise_prob_07

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oEdXHKdjRRyiGMrA6PoEluWjDPRSKQL4
"""

# WAP ask the user to enter names of their 3 favourite movies and store them in a list

movie1 = input("Enter your first favourite movie:  ")
movie2 = input("Enter your second favourite movie:  ")
movie3 = input("Enter your third favourite movie:  ")

favourite_movies = [movie1,movie2,movie3]

print(favourite_movies)